// ionic-react/src/pages/Tab1.tsx
import {
  IonContent,
  IonHeader,
  IonPage,
  IonTitle,
  IonToolbar,
  IonBackButton,
  IonButtons,
  IonButton,
} from "@ionic/react";

import React, { useState, useEffect } from "react";

import ExploreContainer from "../components/ExploreContainer";
import "./Tab1.css";

import { BluetoothSerial } from "@ionic-native/bluetooth-serial";
const bluetoothSerial = BluetoothSerial;

const Tab1: React.FC = () => {
  let [enabled, enabledSet] = useState(false);
  let [list, listSet] = useState<
    { name: string; address: string; id: string; class: Number }[]
  >([]);
  let [status, statusSet] = useState("接続デバイスがありません");

  let [debug, debugSet] = useState("debugArea ");

  const isConnected = () => {
    bluetoothSerial
      .isConnected()
      .then((success) => {
        statusSet(success);
      })
      .catch((failure) => {
        statusSet(failure);
      });
  };

  const btGetList = async (): Promise<void> => {
    await bluetoothSerial
      .isEnabled()
      .then(async (success) => {
        enabled = true;
      })
      .catch(async (failure) => {
        enabled = false;
        alert(`${failure}\nBluetoothをONにしてください`);
        await bluetoothSerial.enable();
      });
    if (enabled) {
      listSet(await bluetoothSerial.list());
    }
  };
  btGetList();

  const btConnect = async (address: string) => {
    bluetoothSerial.connect(address).subscribe((success) => {
      alert(success);
      isConnected();
    });
  };

  const btSend = async (text: string) => {
    await bluetoothSerial
      .isConnected()
      .then(async () => {
        await bluetoothSerial
          .write(text)
          .then(async () => {
            //alert("send");
          })
          .catch(async (failure) => {
            alert(failure);
          });
      })
      .catch(async (failure) => {
        alert("デバイスが接続がされていません");
      });
  };

  /*
  bluetoothSerial.subscribe('\n').subscribe((data)=>{
    alert(`receive\n${data}`)
  })
  */
  useEffect(() => {
    setInterval(() => {
      isConnected();
    }, 1000);
  }, []);

  const color = () => {
    const cc: string = (document.getElementById("color") as HTMLInputElement)
      .value;
    const red = parseInt(cc[1] + cc[2], 16);
    const green = parseInt(cc[3] + cc[4], 16);
    const blue = parseInt(cc[5] + cc[6], 16);
    btSend(`0,${(red / 255) * 1024};`);
    btSend(`1,${(green / 255) * 1024};`);
    btSend(`2,${(blue / 255) * 1024};`);
  };

  return (
    <IonPage>
      <IonHeader>
        <IonToolbar>
          <IonTitle>Tab 1</IonTitle>
        </IonToolbar>
      </IonHeader>
      <IonContent fullscreen>
        <IonHeader collapse="condense">
          <IonToolbar>
            <IonTitle size="large">Tab 1</IonTitle>
          </IonToolbar>
        </IonHeader>
        <ExploreContainer name="Tab 1 page" />
        <p>{debug}</p>
        <IonButton onClick={btGetList}>デバイス再検索</IonButton>
        <br></br>
        <select id="deviceSelect">
          {list.map((v) => {
            return <option value={v.address}>{v.name}</option>;
          })}
        </select>
        <br></br>
        <IonButton
          onClick={() => {
            btConnect(
              (document.getElementById("deviceSelect") as HTMLInputElement)
                .value
            );
          }}
        >
          接続
        </IonButton>
        <br />
        <h3>接続ステータス</h3>
        {status}

        <br />
        <textarea id="textArea"></textarea>
        <IonButton
          onClick={() => {
            btSend(
              (document.getElementById("textArea") as HTMLInputElement).value
            );
          }}
        >
          送信
        </IonButton>
        <br />
        <br />
        <input type="color" id="color"></input>

        <IonButton onClick={color}>color</IonButton>
      </IonContent>
    </IonPage>
  );
};

export default Tab1;

// ionic-vue/src/views/Tab1.vue
<template>
  <ion-page>
    <ion-header>
      <ion-toolbar>
        <ion-title>Tab 1</ion-title>
      </ion-toolbar>
    </ion-header>
    <ion-content :fullscreen="true">
      <ion-header collapse="condense">
        <ion-toolbar>
          <ion-title size="large">Tab 1</ion-title>
        </ion-toolbar>
      </ion-header>

      <ExploreContainer name="Tab 1 page" />
      <p>{{ enabled }}</p>
      <p>{{ isConnected }}</p>
      <p></p>
      <div class="button" @click="btGetList">btGetList</div>
      <div class="button" @click="ax">axios</div>
      <div class="button" @click="btConnectCheck">btConnectCheck</div>
      <div class="button" @click="btSend">btSend</div>
      <div
        class="button"
        v-for="device in list"
        :key="device.address"
        @click="btConnect(device.address)"
      >
        {{ device.name }}
      </div>
      <p>{{ list }}</p>
      <input type="color" id="color" />
      <button @click="color()">colorSend</button>
    </ion-content>
  </ion-page>
</template>

<script lang="ts">
import {
  IonPage,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
} from "@ionic/vue";
import ExploreContainer from "@/components/ExploreContainer.vue";

import axios from "axios";
axios.defaults.headers.post["Access-Control-Allow-Origin"] = "*";

import { BluetoothSerial } from "@ionic-native/bluetooth-serial";

export default {
  name: "Tab1",
  components: {
    ExploreContainer,
    IonHeader,
    IonToolbar,
    IonTitle,
    IonContent,
    IonPage,
  },
  data() {
    return {
      enabled: null,
      isConnected: null,
      text: "text",
      list: {}, // {name:'', address:'', id:'', class:''}
    };
  },
  methods: {
    async btGetList(): Promise<void> {
      await BluetoothSerial.isEnabled()
        .then(() => {
          (this as any).enabled = true;
        })
        .catch(async () => {
          (this as any).enabled = false;
          await BluetoothSerial.enable().then(() => {
            (this as any).enabled = true;
          });
        });

      if ((this as any).enabled) {
        (this as any).list = await BluetoothSerial.list();
      }
    },
    async btConnectCheck(): Promise<void> {
      await BluetoothSerial.isConnected()
        .then(async () => {
          alert("connect");
          (this as any).isConnected = true;
        })
        .catch(async () => {
          alert("disconnect");
          (this as any).isConnected = false;
        });
    },
    async btConnect(address: string): Promise<void> {
      alert(address);
      BluetoothSerial.connect(address).subscribe((success) => {
        alert(success);
      });
      //alert(connect._isScalar);
    },
    async btSend(text: string): Promise<void> {
      await BluetoothSerial.write(text)
        .then(async () => {
          //alert("send");
        })
        .catch(async () => {
          //alert(e);
        });
    },
    async color(): Promise<void> {
      const cc: string = (document.getElementById("color") as HTMLInputElement)
        .value;
      const red = parseInt(cc[1] + cc[2], 16);
      const green = parseInt(cc[3] + cc[4], 16);
      const blue = parseInt(cc[5] + cc[6], 16);
      this.btSend(`0,${(red / 255) * 1024};`);
      this.btSend(`1,${(green / 255) * 1024};`);
      this.btSend(`2,${(blue / 255) * 1024};`);
    },
  },
  ax() {
    alert("axios");
    axios
      .get("https://api.coindesk.com/v1/bpi/currentprice.json")
      .then((res) => {
        alert(res.status);
        alert(res.data);
        alert(JSON.stringify(res.data));
      })
      .catch((err) => {
        alert(err);
      });
  },
};
</script>

<style scoped>
.button {
  height: 100px;
  width: 100px;
  background-color: magenta;
}
</style>
